trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '4eeaf9bc-2832-49c6-8fa2-dcedcd990e08'
  webAppName: 'RemaSampleApp'
  appServicePlan: 'CatServicePlan'

steps:
#Install the Go version
- task: GoTool@0
  displayName: 'Install Go'
  inputs:
    version: '1.17.x'

- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
#Build the Golang application in the REMASample directory
  displayName: 'Build Go application'
  inputs:
    command: 'build'
    arguments: '-o bin/remasample'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzureWebApp@1
#Deploy the built binary to the Azure Web App specified by the webAppName variable, using the AzureWebApp task.
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'webAppLinux'
    appName: $(webAppName)
    package: '$(System.DefaultWorkingDirectory)/bin/remasample'
    runtimeStack: 'GO|latest'
    startUpCommand: './remasample'

# - task: AzureCLI@2
# #Restart the Web App to apply the changes 
#   displayName: 'Restart Web App'
#   inputs:
#     azureSubscription: $(azureSubscription)
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az webapp restart --name $(webAppName) --resource-group $(appServicePlan)'
